package com.arun.helper;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

import org.springframework.util.CollectionUtils;

public class Helper {

	private static final List<String> COUNTRIES = Arrays.asList("Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua & Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia & Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo",
            "Congo Democratic Republic",
            "Costa Rica",
            "Cote d'Ivoire",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "East Timor",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Korea North",
            "Korea South",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macedonia",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Myanmar (Burma)",
            "Namibia",
            "Nauru",
            "Nepal",
            "The Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestinian State",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "The Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "St. Kitts & Nevis",
            "St. Lucia",
            "St. Vincent & The Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome & Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Togo",
            "Tonga",
            "Trinidad & Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States of America",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City (Holy See)",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambia",
            "Zimbabwe");

    private static final List<String> WEATHER_CONDITIONS = Arrays.asList("Partly Sunny",
            "Scattered Thunderstorms",
            "Showers",
            "Scattered Showers",
            "Rain and Snow",
            "Overcast",
            "Light Snow",
            "Freezing Drizzle",
            "Chance of Rain",
            "Sunny",
            "Clear",
            "Mostly Sunny",
            "Partly Cloudy",
            "Mostly Cloudy",
            "Chance of Storm",
            "Rain",
            "Chance of Snow",
            "Cloudy",
            "Mist",
            "Storm",
            "Thunderstorm",
            "Chance of TStorm",
            "Sleet",
            "Snow",
            "Icy",
            "Dust",
            "Fog",
            "Smoke",
            "Haze",
            "Flurries",
            "Light Rain",
            "Snow Showers",
            "Hail");
    
    public static List<String> getCountryList(int limit) {
    	return getCountries(limit, null);
    }
    
    public static List<String> getCountries(int limit, List<String> exclusions) {
    	List<String> countries = new ArrayList<String>(COUNTRIES);
    	if(!CollectionUtils.isEmpty(exclusions)) {
    		countries.removeAll(exclusions);
    	}
    	List<String> randomPick = new ArrayList<String>();
    	for(int i=0;i<limit;i++) {
    		randomPick.add(countries.remove(i));
    	}
    	return randomPick;
    }
    
    public static String getForecast(String destination) {
    	List<String> forecasts = new ArrayList<String>(WEATHER_CONDITIONS);
    	Random rand = new Random(); 
    	return forecasts.remove(rand.nextInt(forecasts.size()-1));
    }
}
